# Site Configuration
baseURL = "/"
languageCode = "en-us"
title = "My New Blog"
theme = "re-terminal"

[params]
  # Site Parameters
  mainSections = ["blog"]
  hideSummary = false
  comments = true
  archives = true
  archiveSection = ["blog"]

  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPageNums = true
  search = true
  searchPlaceholder = "Search..."

  contentTypeName = "blog"

  disableScrollToTop = true
  ReadOtherPosts = "Read other blogs"
  ReadMore = "Read More"

  [languages.en.params.logo]
    logoText = "Harsh's blog"

  [params.homeInfoParams]
    Title = "Hi, I'm Harsh!"
    Content = "Welcome to my blog. This is my personal space where I document my journey and share my thoughts. Find out more [about me](/about/)."

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# Menu Configuration
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 4
